### ISSUE TITLE
tag versions

### ISSUE THREAD

**Issue by christian-bromann** [drudru/ansi_up#12]
Hey,

please make sure to tag every version you publish on bower/npm. Currently everyone who installs this package will always install the #master version of it. That might be not desired in many cases. So after you bump up your version please tag it (via `git tag -a v1.1.4`) and push that tag to github (`git push --tags`).

Thanks!

**Comment by drudru** [comment]
Hi,

Thanks, that is a good point. I will add that to the workflow.

I've updated my latest with tags.

Also, I checked npm, and it will not be affected. They package all the files at the time when I publish a version.

Anyways, thanks for catching this and informing me. I hope this didn't cause you any issues.

Cheers

**Comment by christian-bromann** [comment]
No not at all. Thanks for your effort!
