### ISSUE TITLE
Text from terminal which have no color codes prefixing them are not shown at all. Is that expected ?

### ISSUE THREAD

**Issue by jitenoswal** [drudru/ansi_up#14]
Code - 
```
var stderr = "\n\u001b[1;31mError retrieving a new session from the selenium server\u001b[0m\nError: connect ECONNREFUSED\n    at exports._errnoException (util.js:746:11)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)\n\n\u001b[0;31m\nConnection refused! Is selenium server started?\n\u001b[0m\n";

var html = ansi_up.ansi_to_html(stderr);
```

Output looks like this following image - 

![ansi_to_html](https://cloud.githubusercontent.com/assets/3947512/7504832/17bcb382-f402-11e4-8636-f586f3f14e57.png)

**Comment by drudru** [comment]
hi - yeah - i'm tracking this on a pull request. this is a very interesting regression.

**Comment by jitenoswal** [comment]
Yea it is interesting. Is someone already working on fixing it?

**Comment by drudru** [comment]
Yes, patch should be within a few hours.

**Comment by drudru** [comment]
Hi - ok, tried to repro in my environment and there wasn't an issue.

Can you show me the html returned? Also, a little about your environment. I thought this was the same as the pull request, but it isn't.

**Comment by jitenoswal** [comment]
Oh my god!! This is one of those facepalm moments. 

Thanks for your prompt confirmation that this is a different issue than the pull request you have.

So I see the html is getting generated perfectly fine. But the text in the middle is not visible as its color is same as the background color is.
 
```
<pre id="console">
<span style="color:rgb(255, 85, 85)">Error retrieving a new session from the selenium server</span>
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)

<span style="color:rgb(187, 0, 0)">
Connection refused! Is selenium server started?
</span>
</pre>
```

Solution: I added css to change default color for all text to be green instead of black. I wonder how no one else faced this issue before :P

**Comment by drudru** [comment]
No worries. I guess a lot of people purposely set their text and background for output since a white background tends to not be what ANSI output is generated for.

Also, in the options, you can specify that you want classes instead. In fact, there is an example css/scss in the examples dir that allows you to theme the ansi_up output.

take care,
dru
