### ISSUE TITLE
Reset foreground, background

### ISSUE THREAD

**Issue by jimbauwens** [drudru/ansi_up#21]
I added the following to the code so that resetting of fg and bg values work.

        } else if (num == 39) {
          self.fg = null;
        } else if (num == 49) {
          self.bg = null;

The version I have is 1.2.1 (from bower) and the version indicated in the code here on github is also 1.2.1. However the code isn't the same, so I assume it's not updated. That's also the reason why I didn't do a pull request.

**Comment by eXtreme** [comment]
@jimbauwens I've checked that this fix is still needed. I forced npm to download latest commit (setting `git@github.com:drudru/ansi_up.git#9290483449fa60e4d39d34c76693e1f9b2b792f7` as package version) and without your patch fg and bg are not reset. So I think PR is still needed and then pinging @drudru to merge and release new version. :)

**Comment by drudru** [comment]
Hi @jimbauwens and @eXtreme 

Will get on this today, thx for your patience

**Comment by jimbauwens** [comment]
Great, thanks!

**Comment by eXtreme** [comment]
Cool, thanks!

**Comment by drudru** [comment]
@jimbauwens - hi - please pull the latest from github, send a pull request with the patch plus a test for this. I'll merge it and push a new npm today. Also, please add yourself as a contributor. If you cannot do this today, no problem, I can do it. Just let me know. thx.

**Comment by jimbauwens** [comment]
Hi, I was sleeping but it seems @eXtreme already issued a pull request.

**Comment by drudru** [comment]
All pushed to npm and released on github.

**Comment by eXtreme** [comment]
Thanks @drudru :beers:
