### ISSUE TITLE
Add support for command line piping

### ISSUE THREAD

**Issue by Redsandro** [drudru/ansi_up#27]
Can we add functionality so that when installed globally with `npm -g install ansi_up`, we can pipe input output?

E.g.:

```
 ls -lah --color | ansi_up  > test.html
```

As seen in: 
- [agnoster/ansi2html](https://www.npmjs.com/package/ansi2html) (node)
- [ralphbean/ansi2html](https://github.com/ralphbean/ansi2html) (python)
- [ansi2html.sh](http://www.pixelbeat.org/scripts/ansi2html.sh) (bash)

That would really make this module versatile.

**Comment by drudru** [comment]
@redsandro - that is an interesting suggestion and easy to add.

**Comment by drudru** [comment]
I am closing this issue. However, if someone really wants this and will submit a pull, I will gladly review it.
