### ISSUE TITLE
Newlines ignored

### ISSUE THREAD

**Issue by jyting** [drudru/ansi_up#28]
I'm not 100% sure whether this is a flaw of git's (coloured) ANSI output or otherwise, but this script http://www.pixelbeat.org/scripts/ansi2html.sh more or less provided the newlines.

The issue I'm getting is that everything is concatenated onto one infinitely long line (the specific output being git show console output for large file edits with the colour option on).

Happy to provide more input/information if needed to debug the issue.

**Comment by codecvlt** [comment]
Also noticed this. I seem to remember using the library a few months back and new lines were working.

**Comment by drudru** [comment]
@jyting - some test data would be great. Thanks.

**Comment by scgm11** [comment]
I can see the same, new lines are ignored attach example data

[doc.txt](https://github.com/drudru/ansi_up/files/761026/doc.txt)

**Comment by drudru** [comment]
Hi - what do you mean 'new lines are ignored'?
Do you put the HTML into a pre tag or just a div?

**Comment by drudru** [comment]
Hi - no data. I'm closing this issue. I think the lesson is that users should wrap the output in a PRE or appropriately styled DIV block element.

**Comment by Luiz-N** [comment]
@drudru thanks for making this library. The `pre` tag tip would be good to have in the readme!

**Comment by drudru** [comment]
Thanks Luiz-N - that is fair advice. Will do.
