### ISSUE TITLE
Update License

### ISSUE THREAD

**Issue by mlucool** [drudru/ansi_up#33]
Hi,

Can you please fill in the license field in package.json?

https://docs.npmjs.com/files/package.json#license

**Comment by drudru** [comment]
Will do thx.

**Comment by drudru** [comment]
Just a quick update, testing out a new release on the TypeScript branch. This will be fixed there.

**Comment by drudru** [comment]
Fixed: https://github.com/drudru/ansi_up/commit/c6bb6f04c98020224a42ba84fb3bae2a2c225974
