### ISSUE TITLE
Publish 2.0.0 to NPM

### ISSUE THREAD

**Issue by doughsay** [drudru/ansi_up#39]
The 16 basic ansi colors can be open to interpretation, many themes exist out there defining what the colors look like, so having the `use_classes` option is great for that.

But the 256 color palette and true-color aren't really open for interpretation, they are exact color specifications.  I was wondering if we could add an option to allow for using classes for the basic 16 colors, but when rendering 256 or true-color, use inline styles.

Right now, if you `use_classes` and render 256 color, it renders a class, which could theoretically be used to build a stylesheet for all 256 colors (but that would be tedious).  But for true-color, it only adds a `data-` attribute, which would mean I'd need to add an extra js library of some sort to actually apply the color.  Seems like ansi_up could do that for me instead, right?

**Comment by doughsay** [comment]
So I just noticed that the latest version (2.0.0) actually already does this!  But it's not published to NPM... :(  So I'm changing my issue to be a request to publish the latest version to NPM.  Thanks!

**Comment by drudru** [comment]
Hi doughsay - I will get this pushed next week. Thank you.

**Comment by doughsay** [comment]
Thanks!

**Comment by drudru** [comment]
Ok - npm pushed

**Comment by doughsay** [comment]
@drudru thanks!  have you had a chance to take a look at https://github.com/drudru/ansi_up/pull/41 yet?  I still can't use 2.0.0 directly, I'm still using my fork because of that one issue...
