### ISSUE TITLE
Support for checkmarks

### ISSUE THREAD

**Issue by csvan** [drudru/ansi_up#43]
The character `[32m√` gets rendered as `âˆš`. Is this an issue with ansi_up or the encoding?

**Comment by drudru** [comment]
Thanks - checking into this

**Comment by drudru** [comment]
Ok - I have time for this tomorrow.

**Comment by drudru** [comment]
Hi - I just tested this on my mac in a terminal. I get the checkmark just fine.
Can you give me some more context on this?

**Comment by drudru** [comment]
@csvan - hi pls re-open if you think this is still an issue.
