### ISSUE TITLE
Example for how to use in ES6 / typescript project

### ISSUE THREAD

**Issue by vidartf** [drudru/ansi_up#46]
It would be nice to have an example of how to consume the library in an ES6 project and in a TS project.

**Comment by drudru** [comment]
Hi - I will look into this tomorrow, but I have used it in a TS project. I will need to see what the best practice is these days for TS.

**Comment by drudru** [comment]
Hi @vidartf - if you created these example, I would accept the pull request. 👍

**Comment by vidartf** [comment]
See #47 / #48 for my take on a TS example and a fix for TS typings.

**Comment by drudru** [comment]
Thanks @vidartf - your pull requests were merged.

**Comment by drudru** [comment]
@vidartf 

BTW - a quick heads up - I'm pushing the changes for Bold support. I renamed one of the TypeScript classes. You shouldn't have an issue, but I didn't want this to be a surprise either.
