### ISSUE TITLE
Line feed failure

### ISSUE THREAD

**Issue by hqzh** [drudru/ansi_up#57]
const str = "ERROR[0;31m---------------------------------------------------------------------------[0m[0;31mNameError[0m                                 Traceback (most recent call last)[0;32m<ipython-input-1-14e382bfc774>[0m in [0;36m<module>[0;34m[0m[1;32m    117[0m [0;34m[0m[0m[1;32m    118[0m [0;31m# 输入python脚本，双击左侧算法函数叶子节点引入算法，双击数据叶子节点引入数据[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m[0;32m--> 119[0;31m [0mdfdsf[0m[0;34m[0m[0;34m[0m[0m[0m[0;31mNameError[0m: name 'dfdsf' is not defined"
![issie](https://user-images.githubusercontent.com/26128706/63347338-74dbab80-c389-11e9-86bf-20db3e6a7f63.png)

**Comment by drudru** [comment]
I don't understand the problem.
Could you be more specific about what you are seeing versus what you are expecting?

**Comment by lucafaggianelli** [comment]
I got a problem with linebreaks, I think he's the same issue, basically lines are not wrapped into <p> tags and there is no <br> tag to make new lines in generated HTML, so the entire log is on 1 single line. Is the intended behavior?

**Comment by hqzh** [comment]
> I got a problem with linebreaks, I think he's the same issue, basically lines are not wrapped into
> 
> tags and there is no 
> tag to make new lines in generated HTML, so the entire log is on 1 single line. Is the intended behavior?

It is exactly what I mean

**Comment by lucafaggianelli** [comment]
if you need a quick and dirty fix:
```js
let html = ansi_up.ansi_to_html(log)
html = html.replace(/\n/g, '<br>')
```

**Comment by drudru** [comment]
Or you can put the stuff in <pre> tags. The whitespace is signficant within <pre>

**Comment by hqzh** [comment]
new ansi_up().ansi_to_html(stdout).replace(/\s+/g, '<br>');
