### ISSUE TITLE
How to live stream a log file?

### ISSUE THREAD

**Issue by lucafaggianelli** [drudru/ansi_up#59]
In the readme you speak about a usecase, I'm trying to build the same thing on a Node express server, do you have some code to share? Client and server side? That would be very useful!

https://github.com/drudru/ansi_up#example-of-a-use-case

Thanks

Luca

**Comment by drudru** [comment]
Hi, here is an old example:

https://github.com/drudru/rq/blob/bc46e7e310bb14d86c07084ac21a02ceb6f22b64/code/views/tailview.erb#L28

https://github.com/drudru/rq/blob/bc46e7e310bb14d86c07084ac21a02ceb6f22b64/code/public/js/main.js#L2

It might be an older version of ansi_up in there, but the gist of the idea is the same.

**Comment by lucafaggianelli** [comment]
very useful thank you!

**Comment by drudru** [comment]
:+1:
