### ISSUE TITLE
Document how to set properties

### ISSUE THREAD

**Issue by jennifer-shehane** [drudru/ansi_up#61]
I got a bit confused because someone in our code base had written the below and it was failing to actually use classes.

```js
ansi_up.ansi_to_html('txt', {
  use_classes: true
})
```

I'm not sure if this is because we were converting from 1.3.0 and it *used* to be this way, but there wasn't really any clear documentation on how to set the properties from the Readme when I was trying to fix this.

I eventually found the correct usage from the tests

https://github.com/drudru/ansi_up/blob/aaf041d3e38fcce0de80523e743ada8ab418f9a0/test/ansi_up-test.js#L585

It'd be great to just have an example of setting properties right in the README.md

**Comment by drudru** [comment]
Can you send pull request?

**Comment by drudru** [comment]
Hi - please re-open if this is still an issue.
