### ISSUE TITLE
Works not in browser "Unexpected token 'export'"

### ISSUE THREAD

**Issue by Yorams** [drudru/ansi_up#62]
Hello,

When i want to use the package in the browser i get this error: 
`Unexpected token 'export'`

followed up with this error:
```
slLog_public.js:4 Uncaught ReferenceError: AnsiUp is not defined
    at slLog_public.js:4
```
If i comment out line 348: `export { AnsiUp };` Then it works!

Am i doing something wrong of is this an issue?

**Comment by drudru** [comment]
Hi - this package works in the browser. Please look at the samples.
