### ISSUE TITLE
Handle xterm normal/reset escape sequence

### ISSUE THREAD

**Issue by dosisod** [drudru/ansi_up#72]
I recently found out that xterm uses a weird escape sequence for the normal/reset sequence (aka `sgr0`). Most terminals use `\e[0m`, but xterm uses `\e(B\e[m`:

```
$ env TERM=st-256color tput sgr0 | xxd
00000000: 1b5b 306d                                .[0m
$ env TERM=xterm tput sgr0 | xxd
00000000: 1b28 421b 5b6d                           .(B.[m
```

Here is a small repro:

```html
<html>

<head>
<script src="./ansi_up.js"></script>
</head>

<body>
<pre id="console"></pre>

<script>
const ansi_up = new AnsiUp();

const colors = "\033[1m\033[32mABC";

const xterm = "\033(B\033[mDEF\n";
const notXterm = "\033[0mDEF\n";

const html = ansi_up.ansi_to_html(colors + xterm + colors + notXterm);

document.getElementById("console").innerHTML += html;
</script>
</body>
</html>
```

And this is what it is displaying:

![image](https://user-images.githubusercontent.com/39638017/222271482-1a91ce8a-ac43-40cc-8c77-43b599af0c9e.png)

They both reset the color, though the `(B` bit shouldn't be there in the top line.

**Comment by drudru** [comment]
I don’t think this is a common sequence.
Most apps have moved away from using the term cap database. They usually conform to a popular, common subset.

I personally use xterm-256 in tmux.

what app is sending this sequence?

still, if it is easy, then I don’t see why not.

**Comment by dosisod** [comment]
The program in question is Mypy, specifically [this line](https://github.com/python/mypy/blob/9393c22a1635e9d996a622a09e8464b1b5b51f30/mypy/util.py#L626):

```python
        normal = curses.tigetstr("sgr0")
```

I might open an issue/PR about replacing the curses calls with hardcoded escapes, but I suspect there are lots of other apps out there that are using curses for their escape sequences. A search with [grep.app](https://grep.app/search?q=curses.tigetstr&filter[lang][0]=Python) shows about ~160 open source Python repos are using the `curses.tigetstr()` function.

And I agree that if it is easy to add then it should be added just for better compatibility/coverage.

**Comment by drudru** [comment]
Looking at this today…

**Comment by drudru** [comment]
So, the sequence ESC ( C is actually resetting the character set to USASCII.
ESC ( A - is United Kingdom, C is Finnish.
Interesting.
I think the best strategy is to just ignore it. The data should be UTF8 already.

**Comment by dosisod** [comment]
I agree, ignoring it is probably best.
