### ISSUE TITLE
URL encoding doesn't work with long URLs

### ISSUE THREAD

**Issue by m-murasovs** [drudru/ansi_up#84]
For some reason, the URL RegEx is [restricted to 512 characters](https://github.com/drudru/ansi_up/blob/master/ansi_up.ts#L484C66-L484C66), which causes issues when displaying long URLs.

<img width="447" alt="Screenshot 2023-07-26 at 14 55 05" src="https://github.com/drudru/ansi_up/assets/38246758/a62e4488-1514-406c-86e1-525229e4fb6a">

Shouldn't it be 2048 characters?

**Comment by drudru** [comment]
Curious - are you logging URLs that big?
This was usually meant for terminals.

**Comment by drudru** [comment]
@m-murasovs - any comment?
